services:
  - type: web
    name: flask-bg-remover
    runtime: python
    buildCommand: ""
    startCommand: >
      bash -c "mkdir -p ~/.u2net && 
      wget -q https://github.com/danielgatis/rembg/releases/download/v0.0.0/u2net.onnx -O ~/.u2net/u2net.onnx &&
      gunicorn wsgi:app"
    envVars:
      - key: WEB_CONCURRENCY
        value: "1"
      - key: REMBG_SESSION_CACHE_HOME
        value: "/opt/render/project/.cache"
    plan: free
