services:
  - type: web
    name: flask-bg-remover
    runtime: python
    buildCommand: ""
    startCommand: "gunicorn wsgi:app"
    envVars:
      - key: WEB_CONCURRENCY
        value: "1"
    plan: free
